name: Build Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: retypeapp/action-build@latest
      - uses: retypeapp/action-github-pages@latest
        with:
          branch: "online"
          update-branch: true
